[package]
name = "lobby_system"
version = "0.1.0"
authors = ["gwynart <gwyn.artstyle@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_contrib = "0.4.2"
rand = "0.7.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"